In [14]:
import torch
from torch import nn
import torch.nn.functional as f


In [15]:
sigmoid = nn.Sigmoid()
mse = f.mse_loss

In [16]:
# only one
x = torch.tensor([-3.2,4.1,0.163],requires_grad = False)
w1 = torch.tensor([[0.1,0.3,0.5],[0.2,0.4,0.6]],requires_grad = True)
w2 = torch.tensor([0.7,0.8],requires_grad = True)
y = torch.tensor([2.0],requires_grad = False)

In [24]:
# Batch 
x = torch.tensor([[-3.2,4.1,0.163],[-1.7,3.9,1.35],[-4.16,4.33,0.78],[-2.73,3.14,1.07]],requires_grad = False).reshape(4,3)
w1 = torch.tensor([[0.1,0.3,0.5],[0.2,0.4,0.6]],requires_grad = True)
w2 = torch.tensor([0.7,0.8],requires_grad = True)
y = torch.tensor([2.0,6.2,3.5,4.2],requires_grad = False).reshape(4,1)

In [17]:
def model(x):
    
    h = x@w1.t()
    g = sigmoid(h)
    y = g@w2.t()
    
    
    
    return y

In [18]:
pred = model(x)
pred

tensor(1.1104, grad_fn=<DotBackward0>)

In [19]:
loss = mse(y,pred)
print(loss)
loss.backward()

tensor(0.7913, grad_fn=<MseLossBackward0>)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  """Entry point for launching an IPython kernel.


In [20]:
print(w1.grad)

tensor([[ 0.7866, -1.0078, -0.0401],
        [ 0.8543, -1.0946, -0.0435]])


In [21]:
print(w2.grad)

tensor([-1.2977, -1.3341])


In [22]:
w1-0.5*w1.grad

tensor([[-0.2933,  0.8039,  0.5200],
        [-0.2272,  0.9473,  0.6218]], grad_fn=<SubBackward0>)

In [23]:
w2-0.5*w2.grad

tensor([1.3488, 1.4670], grad_fn=<SubBackward0>)